const colors = {
    white: '#ffffff',
    black: '#000000',
    gray_0: '#d5d5d5',
    gray_1: '#a6a6a6',
    red: '#e84118',
    blue: '#3679fe',
};

export const theme = {
    background: colors.white,
    text: colors.black,
    imageBackground: colors.gray_0,
    label: colors.gray_1,
    inputPlaceholder: colors.gray_1,
    inputBorder: colors.gray_1,
    errorText: colors.red,
    buttonBackground: colors.blue,
    buttonTitle: colors.white,
    buttonUndefilledTitle: colors.blue,
    headerTintColor: colors.black,
    imageButtonBackground: colors.gray_1,
    imageButtonIcon: colors.white,
    spinnerBackground: colors.black,
    spinnerIndicator: colors.white,
    tabActiveColor: colors.blue,
    tabInactiveColor: colors.gray_1,
    buttonLogout: colors.red,
    inputDisabledBackground: colors.gray_0,
    listBorder: colors.gray_0,
    listTime: colors.gray_1,
    listDescription: colors.black,
    listIcon: colors.black,
    
};